### ISSUE TITLE
meep-python did not install

### ISSUE THREAD

**Issue by imansaj** [FilipDominec/python-meep-install#11]
[171009-Ubuntu16.04-x86_64.log](https://github.com/FilipDominec/python-meep-install/files/1987095/171009-Ubuntu16.04-x86_64.log)
Hello I need to use meep in python. this is the log file. It would be really appreciaterd if you could help me. I have anaconda 3 installed on ubuntu 16.04. i can import meep in python, but mpb and other functions like vector3 do not work. Thanks
[vishal.log](https://github.com/FilipDominec/python-meep-install/files/1987085/vishal.log)

**Comment by FilipDominec** [comment]
Hi, first I would like to suggest trying the newer official guide from https://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source

Lately I was too busy to decide about the future of my installer script, so I do not know if it is still the best way to get python-meep working and whether I should update it. If you wish to run the installer, it should work, though:

According to ```tar (child): libctl-3.2.1: Cannot read: Is a directory``` in your log, I suggest to try it anew in an empty directory. There seems to be a clash with an already unpacked ```libctl``` source tree.

**Comment by imansaj** [comment]
ok tnx i will try both
