### ISSUE TITLE
Updates for Fedora 23

### ISSUE THREAD

**Issue by jpturpin** [FilipDominec/python-meep-install#4]
Thanks for providing this script; I've been fighting with building meep-mpi for Fedora for quite some time until I found your project. 

I saw that you had partially written a conversion to allow the use of yum-based systems. I made a few more tweaks, and the script now runs happily to build meep-mpi with openmpi on Fedora 23. 

I've uploaded a diff with the changes I made. Primarily, I updated a few more installation names, the installation commands, and specified the MPI compilers on the autogen command (which gets around the problem seen in the previous issue.

CC=/lib64/openmpi/bin/mpicc CXX=/lib64/openmpi/bin/mpicxx F77=/lib64/openmpi/bin/mpif77 ./autogen.sh $meep_opt --enable-maintainer-mode --enable-shared --prefix=/usr/local  # exits with 1 ?

I was also able to get copies of h5utils and harminv from the fedora copr repository hmaarrfk/meep, so that those tools are available. 

[python-meep-install-fedora23.txt](https://github.com/FilipDominec/python-meep-install/files/302474/python-meep-install-fedora23.txt)

**Comment by FilipDominec** [comment]
Thank you a lot. I will take a look at your kind contribution and update the installer script.

**Comment by FilipDominec** [comment]
Dear @jpturpin , I have tested the script on Fedora 23, but it has failed at several steps. Most notably, it did not find many packages, such as `autotools-dev`, `g++` and `gfortran`. I believe that these are essential for the compilation. Could you please give a hint how you made it work on your system?

**Comment by jpturpin** [comment]
Hi Fillip,

That is strange; those tools are required, as you say. I'll take another 
look. It is possible that those packages were already installed on my 
test machine, and so the dnf install failure didn't cause any trouble. 
I'll see if I can get that straightened out.

Thanks -

-- 
Jeremy Turpin
President, E x H (E cross H)
jpt@exhengineering.com
530-906-7015
www.exhengineering.com

**Comment by FilipDominec** [comment]
@jpturpin , if you resolved this with your certainly better knowledge of Redhat-based Linux distributions, it would be a great contribution for using MEEP on such systems. While you can, of course, issue pull requests, feel free to write your observations here if it is more convenient to you; I can incorporate them into the scripts manually. Thank you.

**Comment by jpturpin** [comment]
@FilipDominec, 
After taking another look at the script, the autotools-dev, g++, and gfortran packages are in the Debian branch of the conditional install statements. Does your fedora system have apt-get installed? That could be messing up the platform detection. I added some additional checks to try to make the fedora/red hat detection more robust, and flowed that result through the rest of the script. A new patch is attached. 

I did double-check the package names, and there were no errors locating any of the specified packages. I also added the pkgconfig (equivalent to pkg-config) to the dependencies list. 

[python-meep-install.sh.fedora23.diff.txt](https://github.com/FilipDominec/python-meep-install/files/304759/python-meep-install.sh.fedora23.diff.txt)

**Comment by FilipDominec** [comment]
I noticed that the patch refers to the original version, not to the already patched. I hope this is what you intended. I will test it out.

**Comment by jpturpin** [comment]
Yes, that is correct; the patch is based on the original git version.

**Comment by FilipDominec** [comment]
The recent compilation outcome is in https://github.com/FilipDominec/python-meep-install/blob/master/logs/fedora23-jpturpin03.log 

It appears there is now a new error in installing the MPI support. I will try to fix it to proceed to the original installation errors.

**Comment by jpturpin** [comment]
Well, that was a syntax error on my part. Line 104 of the patched file: 

if [ -n "$debian" ] || [ "$MPI"="serial" ]; then

should be changed to: 

if [ -n "$debian" ] || [ "$MPI" = "serial" ]; then

(add spaces around the equal sign). The second branch of that if is what needs to be called to build the MPI version in Fedora.

**Comment by FilipDominec** [comment]
Good point, I have fixed it and will test it on a new fresh image of Fedora. Hopefully this test will confirm everything is right!

**Comment by FilipDominec** [comment]
My latest compilation attempt suggests we have fixed the above errors, but it has found another one during the SWIG processing of the MEEP library:

    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1

Full output is at https://raw.githubusercontent.com/FilipDominec/python-meep-install/8673461ba4fc70aa79cb64317c05b3301789c8e4/logs/fedora23-jpturpin05-final.log

**Comment by jpturpin** [comment]
Well, I admit I hadn't actually tried the python build, as I was only interested in the meep executable. 

The missing file that GCC complains about already existed on my system; running
dnf provides /usr/lib/rpm/redhat/redhat-hardened-cc1
said that the redhat-rpm-config package includes that file. 

I corrected the install block for package names, since the packages matplotlib and argparse were not found, and included the redhat-rpm-config package; hopefully this fixes the issues.  

## --- PYTHON-MEEP ------------------------------------------------------------
## Install python-meep dependencies and SWIG
if [ -n "$debian" ]; then
    $INSTALL python-dev python-numpy python-scipy python-matplotlib python-argparse
else
    $INSTALL python-devel numpy scipy python2-matplotlib redhat-rpm-config
    # based on some searching, argparse appears to be included in the default python package on fedora? python-argparse
fi

After making that change, the python bindings appeared to build fine on my system without further adjustments.

**Comment by FilipDominec** [comment]
Excellent, thank you for your kind cooperation. Now the compilation went flawlessly. 

It is not complete success, however. Python is not capable of loading the `meep_mpi` module because it can not find the `libmpi.so` library. Can you use (non-python) MEEP without such a library? Or is it available  in your system?

**Comment by FilipDominec** [comment]
I have found that the `LD_LIBRARY_PATH` variable has to be appended with the directory containing `libmpi.so`, then everything works. I will try to fix this in the scripts. Thank you once again.
