### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by 32nguyen** [FilipDominec/python-meep-install#9]
Sorry, I created this issue just for saying thanks.
I used to have MEEP on 15.10, but failed to install manually on 16.04. You saved my life. I had a issue about import scipy.weave (my scipy is 0.19.1), but I replaced it by import weave. All is good now.
Thanks,

**Comment by FilipDominec** [comment]
I am really glad this project helped you. In fact, there is an unresolved issue with installation in newer versions of Ubuntu (https://github.com/FilipDominec/python-meep-install/issues/7), so I recommend to stay with 16.04 for a while...
